version: "3.9"

services:  
  openai-gpt35:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: gpt-3.5-turbo
      API: openai
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - gpt35_data:/kgfiller/data

  openai-gpt4:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: gpt-4-turbo-preview
      API: openai
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - gpt4_data:/kgfiller/data

  hugging-mistral:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: mistral
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_mistral_data:/kgfiller/data

  hugging-mixtral:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: mixtral
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_mixtral_data:/kgfiller/data

  hugging-openchat:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: openchat
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_openchat_data:/kgfiller/data

  hugging-llama:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: llama-2
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_llama_data:/kgfiller/data

  hugging-hermes:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: nous-hermes
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_hermes_data:/kgfiller/data

  hugging-gemma:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: gemma
      API: hugging
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - hugging_gemma_data:/kgfiller/data

  almaai-vicuna:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      RESTORE_ALL_CACHES: "false"
      ONTO: food
      MODEL: vicuna
      API: almaai
      N_RECIPES: 20
      # LIMIT: 100
    volumes:
      - vicuna_data:/kgfiller/data

secrets:
    all_secrets:
        file: secrets.yml

volumes:
  gpt35_data: {}
  gpt4_data: {}
  hugging_mistral_data: {}
  hugging_mixtral_data: {}
  hugging_openchat_data: {}
  hugging_llama_data: {}
  hugging_hermes_data: {}
  hugging_gemma_data: {}
  vicuna_data: {}
