version: "3.9"

services:  
  openai-gpt35:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      MODEL: gpt-3.5-turbo
      API: openai
      # LIMIT: 100

  hugging-mistral:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      MODEL: mistral
      API: hugging
      # LIMIT: 100

  hugging-falcon:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      MODEL: falcon
      API: hugging
      # LIMIT: 100

  hugging-openchat:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      MODEL: openchat
      API: hugging
      # LIMIT: 100

  almaai-vicuna:
    platform: linux/amd64
    build: .
    secrets:
      - source: all_secrets
        target: /run/secrets/all_secrets.yml
    environment:
      MODEL: vicuna
      API: almaai
      # LIMIT: 100

secrets:
    all_secrets:
        file: secrets.yml
